amcl:
  ros__parameters:
    use_sim_time: true

    # AMCL 기본 설정
    min_particles: 500
    max_particles: 2000

    kld_err: 0.05
    kld_z: 0.99

    update_min_d: 0.2
    update_min_a: 0.1
    resample_interval: 1

    transform_tolerance: 1.0
    recovery_alpha_slow: 0.0
    recovery_alpha_fast: 0.0

    # 레이저 관련 설정
    laser_model_type: "likelihood_field"
    laser_max_beams: 60
    laser_max_range: 12.0
    laser_z_hit: 0.95
    laser_z_short: 0.1
    laser_z_max: 0.05
    laser_z_rand: 0.05
    laser_sigma_hit: 0.2
    laser_lambda_short: 0.1

    # 운동 모델 설정
    odom_model_type: "diff"
    odom_alpha1: 0.2
    odom_alpha2: 0.2
    odom_alpha3: 0.2
    odom_alpha4: 0.2

    # 프레임 설정
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"

    scan_topic: "scan"
    set_initial_pose: true